### ISSUE TITLE
Streamline access to Dining API

### ISSUE THREAD

**Issue by ErikBoesen** [YaleMenus/android#2]
There are a couple opportunities for improvement that I'd like to implement or at least think about regarding how this API fetches data from the `yaledining.org/fasttrack` API. I've been working with the API on [this project](https://github.com/ErikBoesen/yaledining) and have familiarized myself somewhat with its various quirks. The main thing that I want to fix is that this app has some repetition when it comes to API requests. It's not a severe issue, but for example the pattern `JSONArray someData = MainActivity.getJSON("http://www.yaledining.org/fasttrack/some-page.cfm?MENUITEMID=" + aVariable + "&version=3");` followed by iteration through each item each time getting another `JSONArray` are repeated. I would like to add a helper class that handles these requests and allows more abstract fetching of data. I may unbundle that logic into a separate package so that it might be reused in other apps, sort of like the project I mentioned above but for Java instead of Python.

**Comment by amalik12** [comment]
👍
