### ISSUE TITLE
Delay between menu loading animation ending and menu data being displayed

### ISSUE THREAD

**Issue by ErikBoesen** [YaleMenus/android#54]

**Comment by amalik12** [comment]
There's already a loading spinner in the app whenever a dining hall is loaded.

**Comment by ErikBoesen** [comment]
Hm, this is correct. A few people were complaining that there isn't any indication. Perhaps it's off the screen for certain screen sizes?

**Comment by amalik12** [comment]
Actually, when I last tested the app a few days ago, I noticed that there's sometimes a delay between the spinner being cleared at the end of the request and the menu actually being populated, causing a blank screen. There will probably need to be some changes to the logic to prevent this from happening.
